"""
Creador de cuentas TIDAL - Automatización por fases

Fases:
    1. Abrir ventanas en navegador modo incógnito
    2. Aceptar cookies en todas las ventanas
    3. Rellenar emails en formularios de login
    4. Pulsar botón 'Continuar'
    5. Rellenar contraseña, fecha de nacimiento, aceptar términos y pulsar 'Suscríbete'
    6. Verificar estado final, recuperar ventanas incompletas y navegar a link de suscripción
    7. Activar prueba de 60 días y pulsar 'Continuar' en página de planes

Características:
    - Detección de antibot/captcha (pausa manual para resolución)
    - Detección de error 403 CloudFront
    - Verificación rápida (<3s) después de cada fase
    - Recuperación automática de ventanas recargadas/incompletas
    - Navegación automática al link de suscripción
    - Activación automática de prueba de 60 días

Uso:
    python creator_tidal_accounts.py

Archivos requeridos:
    links.txt              - URLs de TIDAL (formato: URL, NombrePerfil)
    emails.txt             - Emails para registro (uno por línea)
    passwords.txt          - Contraseñas (una por línea, orden correspondiente)
    link subscription.txt  - URL de la página de suscripción de TIDAL
"""
from __future__ import annotations

import os
import re
import sys
import time
from pathlib import Path
from typing import Any

from playwright.sync_api import sync_playwright, TimeoutError as PWTimeout, Error as PWError

SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_LINKS_FILE = SCRIPT_DIR / "links.txt"
DEFAULT_EMAILS_FILE = SCRIPT_DIR / "emails.txt"
DEFAULT_PASSWORDS_FILE = SCRIPT_DIR / "passwords.txt"
DEFAULT_LINK_SUBSCRIPTION_FILE = SCRIPT_DIR / "link subscription.txt"


def pausa_manual(subtitulo: str, segundos_sin_tty: float = 90.0) -> None:
    """Detiene el script hasta Enter (o espera fija si no hay consola interactiva)."""
    bar = "=" * 62
    print(f"\n{bar}\n  PAUSA MANUAL — {subtitulo}\n{bar}")
    print(
        "  El script queda detenido. Resuelve captchas/antibot en las ventanas.\n"
        "  Cuando esté todo listo, vuelve a ESTA ventana y pulsa Enter para seguir.\n"
    )
    try:
        if sys.stdin.isatty():
            input("  >>> Pulsa Enter para continuar el script <<<  ")
        else:
            print(f"  (Sin TTY: esperando {segundos_sin_tty:.0f}s y continuando…)\n")
            time.sleep(segundos_sin_tty)
    except EOFError:
        time.sleep(segundos_sin_tty)


def detectar_antibot_tid(page) -> bool:
    """Detecta pantalla de verificación humana / antibot de TIDAL."""
    try:
        if page.is_closed():
            return False
    except PWError:
        return False

    patrones = (
        re.compile(r"nos\s+aseguramos\s+de\s+que", re.I),
        re.compile(r"no\s+a\s+un\s+robot", re.I),
        re.compile(r"desliza\s+hacia\s+la\s+derecha", re.I),
        re.compile(r"velocidad\s+sobrehumana", re.I),
        re.compile(r"making\s+sure.*robot", re.I),
        re.compile(r"not\s+a\s+robot", re.I),
        re.compile(r"slide\s+to\s+(the\s+)?right", re.I),
        re.compile(r"superhuman\s+speed", re.I),
        re.compile(r"captcha", re.I),
        re.compile(r"recaptcha", re.I),
        re.compile(r"soy\s+humano", re.I),
        re.compile(r"i['']?m\s+human", re.I),
    )

    for frame in frames_visibles(page):
        for pat in patrones:
            try:
                loc = frame.get_by_text(pat)
                if loc.count() == 0:
                    continue
                if loc.first.is_visible(timeout=700):
                    return True
            except PWTimeout:
                continue
            except PWError:
                return False
            except Exception:
                continue
    return False


def detectar_error_403_cloudfront(page) -> bool:
    """Detecta página 403 de CloudFront ('Request blocked')."""
    try:
        if page.is_closed():
            return False
    except PWError:
        return False

    try:
        titulo = page.title()
        if re.search(r"403|request could not be satisfied", titulo, re.I):
            return True
    except Exception:
        pass

    patrones = (
        re.compile(r"403\s*ERROR", re.I),
        re.compile(r"the request could not be satisfied", re.I),
        re.compile(r"request blocked", re.I),
        re.compile(r"generated by cloudfront", re.I),
        re.compile(r"we can'?t connect to the server", re.I),
        re.compile(r"demasiado tr[aá]fico", re.I),
        re.compile(r"error 403", re.I),
        re.compile(r"access denied", re.I),
    )

    for frame in frames_visibles(page):
        for pat in patrones:
            try:
                loc = frame.get_by_text(pat)
                if loc.count() == 0:
                    continue
                if loc.first.is_visible(timeout=700):
                    return True
            except PWTimeout:
                continue
            except PWError:
                return False
            except Exception:
                continue

        try:
            txt = frame.locator("body").inner_text(timeout=1500)
            if re.search(r"403\s*ERROR|generated by cloudfront|request blocked|access denied", txt, re.I):
                return True
        except Exception:
            continue
    return False


def detectar_bloqueo_tid(page) -> str | None:
    """Retorna tipo de bloqueo detectado o None si está OK."""
    if detectar_antibot_tid(page):
        return "antibot"
    if detectar_error_403_cloudfront(page):
        return "403 CloudFront"
    return None


def verificar_bloqueos(sesiones: list[dict]) -> list[tuple[int, str, str]]:
    """Verifica si hay bloqueos en las ventanas. Retorna lista de (n, perfil, tipo_bloqueo)."""
    bloqueadas = []
    for sesion in sesiones:
        page = sesion.get("page")
        if not page:
            continue
        try:
            tipo = detectar_bloqueo_tid(page)
            if tipo:
                bloqueadas.append((sesion["n"], sesion["perfil"], tipo))
        except Exception:
            continue
    return bloqueadas


def manejar_bloqueos_y_completitud(
    sesiones: list[dict],
    momento: str,
    fase_verificar: str | None = None,
    datos_verificacion: dict | None = None,
    max_espera_verificacion: float = 3.0,
) -> dict:
    """
    Detecta bloqueos y verifica que la fase anterior se completó correctamente.

    Retorna dict con:
        - bloqueos_resueltos: bool
        - fase_completa: bool
        - ventanas_bloqueadas: list
        - ventanas_incompletas: list
    """
    resultado = {
        "bloqueos_resueltos": True,
        "fase_completa": True,
        "ventanas_bloqueadas": [],
        "ventanas_incompletas": [],
    }

    # 1. Verificar bloqueos
    bloqueadas = verificar_bloqueos(sesiones)
    if bloqueadas:
        tipos = {m for _, _, m in bloqueadas}
        if "403 CloudFront" in tipos and "antibot" in tipos:
            titulo = "BLOQUEO TIDAL (antibot y 403 CloudFront)"
        elif "403 CloudFront" in tipos:
            titulo = "ERROR 403 CLOUDFRONT"
        else:
            titulo = "VERIFICACIÓN ANTI-ROBOT (TIDAL)"

        bar = "=" * 62
        print(f"\n{bar}\n  {titulo} — {momento}\n{bar}")
        for n, perfil, motivo in bloqueadas:
            print(f"   • Ventana [{n}] — {perfil} ({motivo})")
        print(f"\n  Total: {len(bloqueadas)} ventana(s) afectada(s)")

        # Pausa manual para que usuario resuelva
        pausa_manual(f"Resuelve el {titulo} en las ventanas marcadas")

    # 2. Verificar completitud de fase (si se especificó)
    incompletas = []
    if fase_verificar:
        incompletas = verificar_completitud_fase(sesiones, fase_verificar, datos_verificacion)

    # 3. Verificación ultra-rápida combinada (<3s total)
    print(f"\n  Verificando {len(sesiones)} ventanas...")
    inicio = time.time()
    ventanas_revisadas = 0
    errores_bloqueo = []
    errores_completitud = []

    # Calcular tiempo máximo por ventana para cumplir con el límite total
    tiempo_max_por_ventana = max_espera_verificacion / max(len(sesiones), 1)

    for sesion in sesiones:
        if time.time() - inicio > max_espera_verificacion:
            break

        page = sesion.get("page")
        if not page:
            continue

        n, perfil = sesion["n"], sesion["perfil"]
        ventanas_revisadas += 1
        status_parts = []

        try:
            # Verificar bloqueo (ultra-rápido)
            tipo_bloqueo = detectar_bloqueo_tid(page)
            if tipo_bloqueo:
                errores_bloqueo.append((n, perfil, tipo_bloqueo))
                status_parts.append(f"BLOQUEO: {tipo_bloqueo}")

            # Verificar completitud si aplica (ultra-rápido)
            if fase_verificar == "fase3_email":
                email_esperado = datos_verificacion.get("emails", [])[n - 1] if datos_verificacion and n <= len(datos_verificacion.get("emails", [])) else ""
                if email_esperado and not verificar_email_rellenado(page, email_esperado):
                    errores_completitud.append((n, perfil, "email no rellenado"))
                    status_parts.append("FALTA: email")
                elif not email_esperado:
                    status_parts.append("FALTA: email asignado")

            elif fase_verificar == "fase4_continuar":
                if not verificar_pagina_registro(page):
                    errores_completitud.append((n, perfil, "no avanzó a registro"))
                    status_parts.append("FALTA: página registro")

            elif fase_verificar == "fase5_registro":
                estado = verificar_registro_completo(page)
                faltantes = []
                if not estado["password"]:
                    faltantes.append("contraseña")
                if not estado["fecha_nacimiento"]:
                    faltantes.append("fecha")
                if not estado["terminos"]:
                    faltantes.append("términos")
                if not estado["boton_suscribirse"]:
                    faltantes.append("botón bloqueado")
                    status_parts.append("BOTÓN DESHABILITADO (tono oscuro)")
                if faltantes and "botón bloqueado" not in faltantes:
                    errores_completitud.append((n, perfil, f"falta: {', '.join(faltantes)}"))
                    status_parts.append(f"FALTA: {', '.join(faltantes)}")

            if not status_parts:
                status_parts.append("OK ✓")

            # Solo mostrar si hay problemas (para ser más rápido visualmente)
            if len(status_parts) > 1 or status_parts[0] != "OK ✓":
                print(f"   • [{n}] {perfil}: {' | '.join(status_parts)}")

        except Exception:
            # Silenciar errores individuales para velocidad
            pass

        # Pausa mínima proporcional
        if tiempo_max_por_ventana > 0.05:
            time.sleep(tiempo_max_por_ventana * 0.3)  # Usar solo 30% del tiempo asignado

    # Mostrar OK para ventanas que no tuvieron problemas (una sola línea)
    if ventanas_revisadas > 0 and not errores_bloqueo and not errores_completitud:
        print(f"   • Todas las {ventanas_revisadas} ventanas: OK ✓")

    # 4. Resumen
    print(f"\n  Verificación completada ({ventanas_revisadas} ventanas)")

    if errores_bloqueo:
        resultado["bloqueos_resueltos"] = False
        resultado["ventanas_bloqueadas"] = errores_bloqueo
        print(f"\n  ⚠ {len(errores_bloqueo)} ventana(s) aún con bloqueos:")
        for n, perfil, motivo in errores_bloqueo:
            print(f"     • [{n}] {perfil}: {motivo}")

    if errores_completitud:
        resultado["fase_completa"] = False
        resultado["ventanas_incompletas"] = errores_completitud
        print(f"\n  ⚠ {len(errores_completitud)} ventana(s) con fase incompleta:")
        for n, perfil, motivo in errores_completitud:
            print(f"     • [{n}] {perfil}: {motivo}")

    if not errores_bloqueo and not errores_completitud:
        print(f"\n  ✓ Todas las ventanas OK - sin bloqueos ni faltantes")

    return resultado


# Alias para compatibilidad con código existente
def manejar_bloqueos(sesiones: list[dict], momento: str, max_espera_verificacion: float = 3.0) -> bool:
    """
    Función simplificada para compatibilidad.
    Solo verifica bloqueos, no completitud de fase.
    Verificación ultra-rápida (<3s total).
    """
    res = manejar_bloqueos_y_completitud(sesiones, momento, max_espera_verificacion=max_espera_verificacion)
    return res["bloqueos_resueltos"]


def leer_emails(archivo: Path | None = None) -> list[str]:
    """Lee emails desde archivo, uno por línea."""
    archivo = archivo or DEFAULT_EMAILS_FILE
    if not archivo.is_file():
        return []
    emails = []
    with open(archivo, "r", encoding="utf-8") as f:
        for linea in f:
            email = linea.strip()
            if email and not email.startswith("#"):
                emails.append(email)
    return emails


def leer_link_suscripcion(archivo: Path | None = None) -> str | None:
    """Lee el link de suscripción desde archivo."""
    archivo = archivo or DEFAULT_LINK_SUBSCRIPTION_FILE
    if not archivo.is_file():
        return None
    with open(archivo, "r", encoding="utf-8") as f:
        for linea in f:
            url = linea.strip()
            if url and not url.startswith("#"):
                return url
    return None


def leer_passwords(archivo: Path | None = None) -> list[str]:
    """Lee contraseñas desde archivo, una por línea."""
    archivo = archivo or DEFAULT_PASSWORDS_FILE
    if not archivo.is_file():
        return []
    passwords = []
    with open(archivo, "r", encoding="utf-8") as f:
        for linea in f:
            pwd = linea.strip()
            if pwd and not pwd.startswith("#"):
                passwords.append(pwd)
    return passwords


# ============================================================================
# VERIFICACIÓN DE COMPLETITUD DE FASES
# ============================================================================

def verificar_email_rellenado(page, email_esperado: str) -> bool:
    """Verifica ultra-rápido que el campo de email tenga el valor correcto."""
    try:
        if page.is_closed():
            return False
    except PWError:
        return False

    # Selector más común y rápido
    try:
        loc = page.locator('input[type="email"], input[name="email"], input[autocomplete="email"]').first
        if loc.count() and loc.is_visible(timeout=150):
            valor = loc.input_value(timeout=200)
            return valor and valor.lower() == email_esperado.lower()
    except Exception:
        pass
    return False


def verificar_pagina_registro(page) -> bool:
    """Verifica ultra-rápido que estamos en la página de registro."""
    try:
        if page.is_closed():
            return False
    except PWError:
        return False

    # Solo buscar el campo de contraseña (más rápido)
    try:
        loc = page.locator('input[type="password"]').first
        if loc.count() and loc.is_visible(timeout=150):
            return True
    except Exception:
        pass
    return False


def verificar_registro_completo(page) -> dict[str, bool]:
    """Verifica ultra-rápido el estado del formulario de registro."""
    estado = {"password": False, "fecha_nacimiento": False, "terminos": False, "boton_suscribirse": False}

    try:
        if page.is_closed():
            return estado
    except PWError:
        return estado

    # Verificar contraseña (selector directo)
    try:
        loc = page.locator('input[type="password"]').first
        if loc.count():
            val = loc.input_value(timeout=150)
            if val and len(val) > 0:
                estado["password"] = True
    except Exception:
        pass

    # Verificar fecha de nacimiento (solo 1 select con valor)
    try:
        selects = page.locator('select').all()
        con_valor = sum(1 for s in selects if s.input_value(timeout=100).strip())
        if con_valor >= 1:
            estado["fecha_nacimiento"] = True
    except Exception:
        pass

    # Verificar términos aceptados
    try:
        loc = page.locator('input[type="checkbox"]').first
        if loc.count() and loc.is_checked():
            estado["terminos"] = True
    except Exception:
        pass

    # Verificar botón Suscríbete (habilitado = campos completos, tono claro)
    try:
        btn = page.locator('button:has-text("Suscríbete"), button:has-text("Subscribe")').first
        if btn.count() and btn.is_visible(timeout=150):
            # Verificar si el botón está habilitado (no tiene atributo disabled)
            is_enabled = btn.is_enabled(timeout=100)
            # El botón habilitado aparece en tono claro/blanco
            # El botón deshabilitado aparece en tono oscuro/gris
            estado["boton_suscribirse"] = is_enabled
    except Exception:
        pass

    return estado


def verificar_completitud_fase(sesiones: list[dict], fase: str, datos: dict | None = None) -> list[tuple[int, str, str]]:
    """
    Verifica que todas las ventanas hayan completado la fase indicada.
    Retorna lista de ventanas incompletas: (n, perfil, razon).
    """
    incompletas = []

    for sesion in sesiones:
        page = sesion.get("page")
        if not page:
            continue

        n, perfil = sesion["n"], sesion["perfil"]

        try:
            if fase == "fase3_email":
                email_esperado = datos.get("emails", [])[n - 1] if datos and n <= len(datos.get("emails", [])) else ""
                if email_esperado and not verificar_email_rellenado(page, email_esperado):
                    incompletas.append((n, perfil, "email no rellenado o incorrecto"))
                elif not email_esperado:
                    incompletas.append((n, perfil, "no hay email asignado"))

            elif fase == "fase4_continuar":
                if not verificar_pagina_registro(page):
                    incompletas.append((n, perfil, "no se avanzó a página de registro"))

            elif fase == "fase5_registro":
                estado = verificar_registro_completo(page)
                faltantes = []
                if not estado["password"]:
                    faltantes.append("contraseña")
                if not estado["fecha_nacimiento"]:
                    faltantes.append("fecha_nacimiento")
                if not estado["terminos"]:
                    faltantes.append("términos")
                if not estado["boton_suscribirse"]:
                    faltantes.append("botón_suscribirse")

                if faltantes:
                    incompletas.append((n, perfil, f"incompleto: {', '.join(faltantes)}"))

        except Exception as e:
            incompletas.append((n, perfil, f"error al verificar: {e}"))

    return incompletas


def detectar_estado_ventana(page, email_esperado: str = "", password: str = "") -> dict[str, bool]:
    """
    Detecta en qué fase está una ventana y qué campos están completos.
    Retorna estado de cada componente.
    """
    estado = {
        "pagina_login": False,        # Estamos en página de login (campo email visible)
        "email_rellenado": False,     # Email está en el campo
        "pagina_registro": False,     # Estamos en página de registro (campo password visible)
        "password_rellenada": False,  # Password tiene valor
        "fecha_rellenada": False,     # Fecha tiene valor
        "terminos_aceptados": False,  # Checkbox marcado
        "boton_suscribirse_habilitado": False,  # Botón listo para pulsar
        "registro_completado": False, # Ya pasó el registro (no hay formulario)
    }

    try:
        if page.is_closed():
            return estado
    except PWError:
        return estado

    try:
        # Detectar página de login (campo email visible)
        email_field = page.locator('input[type="email"], input[name="email"]').first
        if email_field.count() and email_field.is_visible(timeout=100):
            estado["pagina_login"] = True
            val = email_field.input_value(timeout=100)
            if val and email_esperado and val.lower() == email_esperado.lower():
                estado["email_rellenado"] = True
            elif val:
                estado["email_rellenado"] = True  # Tiene algún email

        # Detectar página de registro (campo password visible)
        pwd_field = page.locator('input[type="password"]').first
        if pwd_field.count() and pwd_field.is_visible(timeout=100):
            estado["pagina_registro"] = True
            val = pwd_field.input_value(timeout=100)
            if val and len(val) > 0:
                estado["password_rellenada"] = True

        # Verificar fecha (selects con valores)
        try:
            selects = page.locator('select').all()
            con_valor = sum(1 for s in selects if s.input_value(timeout=100).strip())
            if con_valor >= 1:
                estado["fecha_rellenada"] = True
        except Exception:
            pass

        # Verificar términos
        try:
            cb = page.locator('input[type="checkbox"]').first
            if cb.count() and cb.is_checked():
                estado["terminos_aceptados"] = True
        except Exception:
            pass

        # Verificar botón Suscríbete (inlineado para evitar dependencia de orden)
        try:
            btn = page.locator('button:has-text("Suscríbete"), button:has-text("Subscribe")').first
            if btn.count() and btn.is_visible(timeout=100):
                estado["boton_suscribirse_habilitado"] = btn.is_enabled(timeout=100)
        except Exception:
            pass

        # Detectar si ya pasó el registro (no hay formularios típicos)
        if not estado["pagina_login"] and not estado["pagina_registro"]:
            # Podría ser página post-registro o de suscripción
            estado["registro_completado"] = True

    except Exception:
        pass

    return estado


def recuperar_ventana(sesion: dict, email: str, password: str, max_intentos: int = 2) -> bool:
    """
    Recupera una ventana que se recargó o quedó incompleta.
    Re-ejecuta las fases necesarias según el estado detectado.
    Retorna True si la ventana está lista para ir al link de suscripción.
    """
    page = sesion.get("page")
    if not page:
        return False

    n, perfil = sesion["n"], sesion["perfil"]

    for intento in range(max_intentos):
        estado = detectar_estado_ventana(page, email, password)

        # Caso 1: Estamos en página de login y falta email
        if estado["pagina_login"] and not estado["email_rellenado"]:
            if email and rellenar_email_login(page, email):
                time.sleep(0.3)
                pulsar_boton_por_texto(page, (
                    re.compile(r"^\s*continuar\s*$", re.I),
                    re.compile(r"^\s*continue\s*$", re.I),
                ))
                time.sleep(1.0)  # Esperar carga de página de registro
                continue

        # Caso 2: Estamos en página de registro pero incompleta
        if estado["pagina_registro"]:
            # Rellenar password si falta
            if not estado["password_rellenada"] and password:
                try:
                    loc = page.locator('input[type="password"]').first
                    if loc.count():
                        loc.fill(password, timeout=1000, force=True)
                        time.sleep(0.2)
                except Exception:
                    pass

            # Rellenar fecha si falta
            if not estado["fecha_rellenada"]:
                import random
                dia, mes, año = str(random.randint(1, 28)), str(random.randint(1, 12)), str(random.randint(1970, 2005))
                try:
                    selects = page.locator('select').all()
                    for i, sel in enumerate(selects[:3]):
                        try:
                            val = sel.input_value(timeout=100)
                            if not val or not val.strip():
                                sel.select_option([dia, mes, año][i])
                                time.sleep(0.1)
                        except Exception:
                            continue
                except Exception:
                    pass

            # Aceptar términos si faltan (usando force=True para mayor fiabilidad)
            if not estado["terminos_aceptados"]:
                try:
                    # Intentar primero la función mejorada
                    if not aceptar_terminos_privacidad(page):
                        # Fallback: marcar todos los checkboxes no marcados
                        checkboxes = page.locator('input[type="checkbox"]').all()
                        for cb in checkboxes:
                            try:
                                if cb.is_visible(timeout=200) and not cb.is_checked():
                                    cb.check(timeout=2000, force=True)
                                    time.sleep(0.2)
                            except Exception:
                                continue
                except Exception:
                    pass

            # Verificar si el botón se habilitó (inlineado)
            time.sleep(0.3)
            habilitado = False
            try:
                btn = page.locator('button:has-text("Suscríbete"), button:has-text("Subscribe")').first
                if btn.count() and btn.is_visible(timeout=200):
                    habilitado = btn.is_enabled(timeout=200)
            except Exception:
                pass
            
            if habilitado:
                # Pulsar Suscríbete
                pulsar_suscribirse(page)
                time.sleep(1.0)  # Esperar redirección
                return True

        # Caso 3: Ya pasó el registro
        if estado["registro_completado"] and not estado["pagina_login"] and not estado["pagina_registro"]:
            return True

        time.sleep(0.5)

    # Verificación final
    estado_final = detectar_estado_ventana(page, email, password)
    return estado_final["registro_completado"] or estado_final["boton_suscribirse_habilitado"]


def parsear_linea_link(linea: str) -> tuple[str, str]:
    """Parsea linea formato 'URL, Perfil' -> (url, nombre_perfil)."""
    for sep in (",", ";", "|"):
        if sep in linea:
            partes = linea.split(sep, 1)
            return partes[0].strip(), partes[1].strip()
    return linea.strip(), "Perfil"


def leer_sesiones(archivo: Path | None = None) -> list[dict[str, Any]]:
    """Lee archivo links.txt y retorna lista de sesiones con url y perfil."""
    archivo = archivo or DEFAULT_LINKS_FILE
    if not archivo.is_file():
        print(f"Archivo no encontrado: {archivo}")
        return []

    sesiones = []
    with open(archivo, "r", encoding="utf-8") as f:
        for linea in f:
            linea = linea.strip()
            if not linea or linea.startswith("#"):
                continue
            url, perfil = parsear_linea_link(linea)
            sesiones.append({"url": url, "perfil": perfil, "page": None, "n": len(sesiones) + 1})
    return sesiones


def frames_visibles(page):
    """Retorna todos los frames visibles de la página."""
    try:
        return list(page.frames)
    except PWError:
        return []


def intentar_aceptar_cookies(page) -> bool:
    """Intenta aceptar cookies en la página TIDAL."""
    try:
        if page.is_closed():
            return False
    except PWError:
        return False

    # Patrones de texto para botón Aceptar
    patrones_aceptar = (
        re.compile(r"^\s*aceptar\s*$", re.I),
        re.compile(r"^\s*aceptar todo", re.I),
        re.compile(r"^\s*aceptar todas", re.I),
        re.compile(r"^\s*accept\s*$", re.I),
        re.compile(r"^\s*accept all", re.I),
        re.compile(r"^\s*i agree", re.I),
        re.compile(r"^\s*allow all", re.I),
        re.compile(r"^\s*consentir", re.I),
    )

    # Selectores CSS comunes de cookies
    selectores_css = [
        "#onetrust-accept-btn-handler",
        "button#onetrust-accept-btn-handler",
        "button.sp_choice_type_11",
        "button[data-testid*='accept' i]",
        '[id*="accept" i][id*="cookie" i]',
        '[class*="cookie" i] button[class*="accept" i]',
        'button[id*="accept" i]',
        '[aria-label*="Aceptar" i]',
        '[aria-label*="Accept" i]',
    ]

    for frame in frames_visibles(page):
        # Intentar por texto de botón
        for patron in patrones_aceptar:
            try:
                loc = frame.get_by_role("button", name=patron)
                if loc.count() == 0:
                    continue
                btn = loc.last if loc.count() > 1 else loc.first
                btn.scroll_into_view_if_needed(timeout=1200)
                if btn.is_visible(timeout=700):
                    btn.click(timeout=2200)
                    return True
            except PWTimeout:
                continue
            except PWError:
                return False
            except Exception:
                continue

        # Intentar por selectores CSS
        for sel in selectores_css:
            try:
                loc = frame.locator(sel).last
                if loc.count() and loc.is_visible(timeout=450):
                    loc.scroll_into_view_if_needed(timeout=900)
                    loc.click(timeout=2200)
                    return True
            except PWTimeout:
                continue
            except PWError:
                return False
            except Exception:
                continue

        # Buscar texto "Aceptar" y clickear su elemento padre
        for patron in (re.compile(r"^\s*aceptar\s*$", re.I), re.compile(r"^\s*accept\s*$", re.I)):
            try:
                items = frame.get_by_text(patron).all()
                for item in items:
                    try:
                        if not item.is_visible(timeout=320):
                            continue
                        # Buscar botón ancestro
                        el = item.locator('xpath=ancestor-or-self::button[1] | ancestor-or-self::*[@role="button"][1]')
                        if el.count():
                            el.first.click(timeout=2000)
                            return True
                    except Exception:
                        continue
            except Exception:
                continue

    return False


def aceptar_cookies_con_espera(page, intentos: int = 4, pausa_s: float = 0.3) -> bool:
    """Intenta aceptar cookies múltiples veces con espera."""
    for _ in range(intentos):
        try:
            if page.is_closed():
                return False
        except PWError:
            return False

        if intentar_aceptar_cookies(page):
            return True
        time.sleep(pausa_s)
    return False


def encontrar_chrome() -> str | None:
    """Busca la ruta del ejecutable de Chrome instalado en el sistema."""
    posibles_rutas = [
        # Windows - Chrome estándar
        Path(os.environ.get("PROGRAMFILES", r"C:\Program Files")) / "Google" / "Chrome" / "Application" / "chrome.exe",
        Path(os.environ.get("PROGRAMFILES(X86)", r"C:\Program Files (x86)")) / "Google" / "Chrome" / "Application" / "chrome.exe",
        Path(os.environ.get("LOCALAPPDATA", r"C:\Users\Default\AppData\Local")) / "Google" / "Chrome" / "Application" / "chrome.exe",
        # Windows - Chrome Beta/Dev/Canary
        Path(os.environ.get("PROGRAMFILES", r"C:\Program Files")) / "Google" / "Chrome Beta" / "Application" / "chrome.exe",
        Path(os.environ.get("LOCALAPPDATA", r"C:\Users\Default\AppData\Local")) / "Google" / "Chrome SxS" / "Application" / "chrome.exe",
        # Edge como fallback (también basado en Chromium)
        Path(os.environ.get("PROGRAMFILES", r"C:\Program Files")) / "Microsoft" / "Edge" / "Application" / "msedge.exe",
        Path(os.environ.get("PROGRAMFILES(X86)", r"C:\Program Files (x86)")) / "Microsoft" / "Edge" / "Application" / "msedge.exe",
    ]

    for ruta in posibles_rutas:
        if ruta.exists():
            return str(ruta)

    return None


def fase_1_abrir_ventanas(playwright, sesiones: list[dict]) -> list[dict]:
    """
    Fase 1: Abre ventanas en modo incógnito usando Chrome REAL (no Chromium).
    CADA sesión tiene su propio contexto aislado.
    Retorna sesiones_actualizadas.
    """
    if not sesiones:
        print("No hay sesiones para abrir. Agrega URLs a links.txt")
        return sesiones

    # Buscar Chrome instalado
    chrome_path = encontrar_chrome()
    if not chrome_path:
        print("\n⚠ ERROR: No se encontró Google Chrome instalado.")
        print("  Instala Chrome desde: https://www.google.com/chrome/")
        print("  O especifica la ruta manualmente en el código.")
        return sesiones

    print(f"\n=== FASE 1: Abriendo {len(sesiones)} ventana(s) con Chrome REAL ===")
    print(f"Chrome detectado: {chrome_path}")
    print("Cada perfil usa contexto aislado (anti-detección)\n")

    # Argumentos anti-detección para Chrome real
    args_anti_deteccion = [
        "--incognito",
        "--disable-blink-features=AutomationControlled",
        "--disable-web-security",
        "--disable-features=IsolateOrigins,site-per-process",
        "--disable-site-isolation-trials",
        "--disable-dev-shm-usage",
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-accelerated-2d-canvas",
        "--disable-gpu",
        "--window-size=1920,1080",
        "--start-maximized",
        "--force-device-scale-factor=1",
    ]

    browser = playwright.chromium.launch(
        headless=False,
        executable_path=chrome_path,
        args=args_anti_deteccion,
    )

    for sesion in sesiones:
        try:
            # Crear un NUEVO contexto para cada sesión (perfil aislado)
            context = browser.new_context()
            page = context.new_page()
            page.goto(sesion["url"], wait_until="domcontentloaded", timeout=30000)

            sesion["page"] = page
            sesion["browser"] = browser
            sesion["context"] = context  # Cada uno tiene su propio contexto

            print(f"[{sesion['n']}] {sesion['perfil']}: abierta en perfil aislado ✓")
            time.sleep(0.3)
        except Exception as e:
            print(f"[{sesion['n']}] Error abriendo {sesion['perfil']}: {e}")

    abiertas = len([s for s in sesiones if s.get("page")])
    print(f"\n✓ Fase 1 completada: {abiertas}/{len(sesiones)} perfil(es) abierto(s)")
    print("  Cada perfil está completamente aislado (cookies, almacenamiento independiente)")
    return sesiones


def fase_2_aceptar_cookies(sesiones: list[dict]) -> int:
    """
    Fase 2: Acepta cookies en todas las ventanas abiertas.
    Retorna el número de ventanas donde se aceptaron cookies.
    """
    sesiones_validas = [s for s in sesiones if s.get("page")]
    if not sesiones_validas:
        print("No hay ventanas abiertas para aceptar cookies.")
        return 0

    print(f"\n=== FASE 2: Aceptando cookies en {len(sesiones_validas)} ventana(s) ===\n")

    # Esperar a que cargue el banner de cookies
    time.sleep(1.5)

    exitosos = 0
    for sesion in sesiones_validas:
        page = sesion["page"]
        try:
            if aceptar_cookies_con_espera(page, intentos=3, pausa_s=0.4):
                print(f"[{sesion['n']}] {sesion['perfil']}: cookies aceptadas ✓")
                exitosos += 1
            else:
                print(f"[{sesion['n']}] {sesion['perfil']}: no se detectó banner de cookies")
        except Exception as e:
            print(f"[{sesion['n']}] {sesion['perfil']}: error - {e}")

    print(f"\n✓ Fase 2 completada: cookies aceptadas en {exitosos}/{len(sesiones_validas)} ventana(s)")
    return exitosos


def rellenar_email_login(page, email: str) -> bool:
    """Rellena el campo de email en el formulario de login TIDAL."""
    if not email:
        return False

    try:
        if page.is_closed():
            return False
    except PWError:
        return False

    # Esperar carga del DOM
    try:
        page.wait_for_load_state("domcontentloaded", timeout=8000)
    except PWTimeout:
        pass
    except PWError:
        return False

    # Esperar iframe si existe
    try:
        page.wait_for_selector("iframe", timeout=1800)
    except PWTimeout:
        pass

    time.sleep(0.3)

    selectores = [
        'input[type="email"]',
        'input[type="text"]',
        'input[name="email"]',
        'input[name="username"]',
        'input[autocomplete="email"]',
        'input[id*="email" i]',
        'input[id*="username" i]',
        'input[placeholder*="mail" i]',
        'input[placeholder*="email" i]',
        'input[placeholder*="correo" i]',
        'input[placeholder*="usuario" i]',
        'input[data-testid*="email" i]',
    ]

    for frame in frames_visibles(page):
        # Intentar por placeholder
        try:
            plac_pat = re.compile(r"(email|mail|correo|usuario|username|introduce)", re.I)
            loc = frame.get_by_placeholder(plac_pat).first
            if loc.count() and loc.is_visible(timeout=500):
                loc.scroll_into_view_if_needed(timeout=800)
                loc.click(timeout=800)
                loc.fill(email, timeout=2200, force=True)
                return True
        except PWTimeout:
            pass
        except PWError:
            return False
        except Exception:
            pass

        # Intentar por label
        for rx in (re.compile(r"(correo|email|usuario|username|identif)", re.I),):
            try:
                loc = frame.get_by_label(rx).first
                if loc.count() and loc.is_visible(timeout=500):
                    loc.scroll_into_view_if_needed(timeout=800)
                    loc.click(timeout=800)
                    loc.fill(email, timeout=2200, force=True)
                    return True
            except PWTimeout:
                continue
            except PWError:
                return False
            except Exception:
                continue

        # Intentar por selectores CSS
        for sel in selectores:
            try:
                loc = frame.locator(sel).first
                if not loc.count():
                    continue
                if not loc.is_visible(timeout=400):
                    continue
                loc.scroll_into_view_if_needed(timeout=800)
                loc.click(timeout=800)
                loc.fill(email, timeout=2200, force=True)
                return True
            except PWTimeout:
                continue
            except PWError:
                return False
            except Exception:
                continue

    return False


def fase_3_rellenar_emails(sesiones: list[dict], emails: list[str]) -> int:
    """
    Fase 3: Rellena los correos en el formulario de login de cada ventana.
    Retorna el número de ventanas donde se rellenó el email.
    """
    sesiones_validas = [s for s in sesiones if s.get("page")]
    if not sesiones_validas:
        print("No hay ventanas abiertas para rellenar emails.")
        return 0

    print(f"\n=== FASE 3: Rellenando emails en {len(sesiones_validas)} ventana(s) ===\n")

    exitosos = 0
    for i, sesion in enumerate(sesiones_validas):
        page = sesion["page"]
        email = emails[i] if i < len(emails) else ""

        if not email:
            print(f"[{sesion['n']}] {sesion['perfil']}: no hay email asignado")
            continue

        try:
            if rellenar_email_login(page, email):
                print(f"[{sesion['n']}] {sesion['perfil']}: email rellenado ✓")
                exitosos += 1
            else:
                print(f"[{sesion['n']}] {sesion['perfil']}: no se pudo rellenar el email")
        except Exception as e:
            print(f"[{sesion['n']}] {sesion['perfil']}: error - {e}")

        time.sleep(0.2)

    print(f"\n✓ Fase 3 completada: emails rellenados en {exitosos}/{len(sesiones_validas)} ventana(s)")
    return exitosos


def pulsar_boton_por_texto(page, patrones: tuple, timeout_ms: int = 800) -> bool:
    """Busca y pulsa un botón que coincida con algún patrón de texto."""
    try:
        if page.is_closed():
            return False
    except PWError:
        return False

    for frame in frames_visibles(page):
        for patron in patrones:
            try:
                loc = frame.get_by_role("button", name=patron)
                if loc.count() == 0:
                    continue
                btn = loc.last if loc.count() > 1 else loc.first
                btn.scroll_into_view_if_needed(timeout=1200)
                if btn.is_visible(timeout=700):
                    btn.click(timeout=2200)
                    return True
            except PWTimeout:
                continue
            except PWError:
                return False
            except Exception:
                continue
    return False


def fase_4_pulsar_continuar(sesiones: list[dict]) -> int:
    """
    Fase 4: Pulsa el botón 'Continuar' en el formulario de email.
    Retorna el número de ventanas donde se pulsó el botón.
    """
    sesiones_validas = [s for s in sesiones if s.get("page")]
    if not sesiones_validas:
        print("No hay ventanas abiertas para pulsar Continuar.")
        return 0

    print(f"\n=== FASE 4: Pulsando 'Continuar' en {len(sesiones_validas)} ventana(s) ===\n")

    patrones = (
        re.compile(r"^\s*continuar\s*$", re.I),
        re.compile(r"^\s*continue\s*$", re.I),
        re.compile(r"^\s*siguiente\s*$", re.I),
        re.compile(r"^\s*next\s*$", re.I),
    )

    exitosos = 0
    for sesion in sesiones_validas:
        page = sesion["page"]
        try:
            if pulsar_boton_por_texto(page, patrones):
                print(f"[{sesion['n']}] {sesion['perfil']}: botón 'Continuar' pulsado ✓")
                exitosos += 1
            else:
                print(f"[{sesion['n']}] {sesion['perfil']}: no se encontró botón 'Continuar'")
        except Exception as e:
            print(f"[{sesion['n']}] {sesion['perfil']}: error - {e}")
        time.sleep(0.2)

    # Esperar a que cargue la siguiente página
    time.sleep(1.5)

    print(f"\n✓ Fase 4 completada: 'Continuar' pulsado en {exitosos}/{len(sesiones_validas)} ventana(s)")
    return exitosos


def rellenar_contraseña_login(page, password: str) -> bool:
    """Rellena el campo de contraseña en el formulario de registro TIDAL."""
    if not password:
        return False

    try:
        if page.is_closed():
            return False
    except PWError:
        return False

    selectores = [
        'input[type="password"]',
        'input[name="password"]',
        'input[autocomplete="new-password"]',
        'input[autocomplete="current-password"]',
        'input[id*="password" i]',
        'input[id*="contrasena" i]',
        'input[placeholder*="password" i]',
        'input[placeholder*="contraseña" i]',
        'input[data-testid*="password" i]',
    ]

    for frame in frames_visibles(page):
        # Intentar por placeholder
        try:
            plac_pat = re.compile(r"(password|contraseña|pass|pwd)", re.I)
            loc = frame.get_by_placeholder(plac_pat).first
            if loc.count() and loc.is_visible(timeout=500):
                loc.scroll_into_view_if_needed(timeout=800)
                loc.click(timeout=800)
                loc.fill(password, timeout=2200, force=True)
                return True
        except PWTimeout:
            pass
        except PWError:
            return False
        except Exception:
            pass

        # Intentar por label
        for rx in (re.compile(r"(contraseña|password|pass|pwd)", re.I),):
            try:
                loc = frame.get_by_label(rx).first
                if loc.count() and loc.is_visible(timeout=500):
                    loc.scroll_into_view_if_needed(timeout=800)
                    loc.click(timeout=800)
                    loc.fill(password, timeout=2200, force=True)
                    return True
            except PWTimeout:
                continue
            except PWError:
                return False
            except Exception:
                continue

        # Intentar por selectores CSS
        for sel in selectores:
            try:
                loc = frame.locator(sel).first
                if not loc.count():
                    continue
                if not loc.is_visible(timeout=400):
                    continue
                loc.scroll_into_view_if_needed(timeout=800)
                loc.click(timeout=800)
                loc.fill(password, timeout=2200, force=True)
                return True
            except PWTimeout:
                continue
            except PWError:
                return False
            except Exception:
                continue

    return False


def rellenar_fecha_nacimiento(page) -> bool:
    """Rellena campos de fecha de nacimiento con valores aleatorios válidos."""
    import random

    try:
        if page.is_closed():
            return False
    except PWError:
        return False

    # Valores aleatorios para adulto (18-50 años)
    dia = random.randint(1, 28)
    mes = random.randint(1, 12)
    año = random.randint(1970, 2005)

    selectores_dia = [
        'select[name*="day" i]', 'select[name*="dia" i]',
        'select[id*="day" i]', 'select[id*="dia" i]',
        'select[placeholder*="día" i]', 'select[placeholder*="day" i]',
    ]
    selectores_mes = [
        'select[name*="month" i]', 'select[name*="mes" i]',
        'select[id*="month" i]', 'select[id*="mes" i]',
        'select[placeholder*="mes" i]', 'select[placeholder*="month" i]',
    ]
    selectores_año = [
        'select[name*="year" i]', 'select[name*="año" i]',
        'select[id*="year" i]', 'select[id*="año" i]',
        'select[placeholder*="año" i]', 'select[placeholder*="year" i]',
    ]

    exitosos = 0

    for frame in frames_visibles(page):
        # Día
        for sel in selectores_dia:
            try:
                loc = frame.locator(sel).first
                if loc.count() and loc.is_visible(timeout=400):
                    loc.select_option(str(dia))
                    exitosos += 1
                    break
            except Exception:
                continue

        # Mes
        for sel in selectores_mes:
            try:
                loc = frame.locator(sel).first
                if loc.count() and loc.is_visible(timeout=400):
                    loc.select_option(str(mes))
                    exitosos += 1
                    break
            except Exception:
                continue

        # Año
        for sel in selectores_año:
            try:
                loc = frame.locator(sel).first
                if loc.count() and loc.is_visible(timeout=400):
                    loc.select_option(str(año))
                    exitosos += 1
                    break
            except Exception:
                continue

    return exitosos >= 2  # Considera éxito si al menos 2 campos se llenaron


def aceptar_terminos_privacidad(page) -> bool:
    """Marca el checkbox de términos de uso y aviso de privacidad."""
    try:
        if page.is_closed():
            return False
    except PWError:
        return False

    # Patrones de texto para encontrar la sección de términos
    patrones_texto = [
        re.compile(r"términos\s+de\s+uso", re.I),
        re.compile(r"aviso\s+de\s+privacidad", re.I),
        re.compile(r"terms\s+of\s+use", re.I),
        re.compile(r"privacy\s+policy", re.I),
        re.compile(r"al\s+registrarte.*confirmas", re.I),
        re.compile(r"by\s+registering.*agree", re.I),
        re.compile(r"aceptas\s+las\s+términos", re.I),
        re.compile(r"acepto\s+los", re.I),
        re.compile(r"i\s+agree", re.I),
    ]

    # Estrategia 1: Buscar checkbox cerca del texto de términos
    for patron in patrones_texto:
        try:
            # Buscar el texto de términos en la página
            texto_terminos = page.get_by_text(patron).first
            if texto_terminos.count():
                # Intentar varias formas de encontrar el checkbox relacionado
                selectores_cercanos = [
                    # Checkbox en el mismo label/div padre (más común)
                    'xpath=ancestor::label//input[@type="checkbox"]',
                    'xpath=ancestor::div[contains(@class, "checkbox")]//input[@type="checkbox"]',
                    'xpath=ancestor::div[1]//input[@type="checkbox"]',
                    # Checkbox hermano (antes o después del texto)
                    'xpath=preceding-sibling::input[@type="checkbox"]',
                    'xpath=following-sibling::input[@type="checkbox"]',
                    'xpath=preceding::input[@type="checkbox"][1]',
                    'xpath=following::input[@type="checkbox"][1]',
                    # Checkbox dentro del contenedor padre
                    'xpath=parent::label//input[@type="checkbox"]',
                    'xpath=parent::div//input[@type="checkbox"]',
                ]
                for selector_xpath in selectores_cercanos:
                    try:
                        checkbox = texto_terminos.locator(selector_xpath).first
                        if checkbox.count() and checkbox.is_visible(timeout=500):
                            if not checkbox.is_checked():
                                checkbox.check(timeout=2000, force=True)
                            return True
                    except Exception:
                        continue
        except Exception:
            continue

    # Estrategia 2: Buscar TODOS los checkboxes y marcar el que parezca ser de términos
    try:
        # Obtener todos los checkboxes de la página
        all_checkboxes = page.locator('input[type="checkbox"]').all()
        for i, checkbox in enumerate(all_checkboxes):
            try:
                if checkbox.is_visible(timeout=300) and not checkbox.is_checked():
                    # Verificar si está cerca de texto de términos (heurística)
                    checkbox.check(timeout=2000, force=True)
                    # Si no lanzó excepción, asumimos éxito
                    return True
            except Exception:
                continue
    except Exception:
        pass

    # Estrategia 3: Click directo por coordenada relativa al texto (último recurso)
    for patron in patrones_texto:
        try:
            texto_terminos = page.get_by_text(patron).first
            if texto_terminos.count():
                # Intentar hacer click en la posición típica del checkbox (izquierda del texto)
                box = texto_terminos.bounding_box()
                if box:
                    # Click 30px a la izquierda del centro del texto (donde suele estar el checkbox)
                    page.mouse.click(box["x"] - 30, box["y"] + box["height"] / 2)
                    return True
        except Exception:
            continue

    return False


def pulsar_suscribirse(page) -> bool:
    """Pulsa el botón 'Suscríbete' o similar."""
    patrones = (
        re.compile(r"^\s*suscríbete\s*$", re.I),
        re.compile(r"^\s*suscribete\s*$", re.I),
        re.compile(r"^\s*subscribe\s*$", re.I),
        re.compile(r"^\s*crear\s+cuenta\s*$", re.I),
        re.compile(r"^\s*registrarse\s*$", re.I),
        re.compile(r"^\s*sign\s+up\s*$", re.I),
        re.compile(r"^\s*register\s*$", re.I),
    )
    return pulsar_boton_por_texto(page, patrones, timeout_ms=1000)


def verificar_boton_suscribirse_habilitado(page) -> tuple[bool, bool]:
    """
    Verifica el estado del botón Suscríbete.
    Retorna (visible, habilitado).
    - visible: el botón existe y está en la página
    - habilitado: el botón está activo (campos completos) o deshabilitado (faltan campos)
    """
    try:
        if page.is_closed():
            return False, False
    except PWError:
        return False, False

    try:
        btn = page.locator('button:has-text("Suscríbete"), button:has-text("Subscribe")').first
        if not btn.count():
            return False, False

        visible = btn.is_visible(timeout=200)
        if not visible:
            return False, False

        habilitado = btn.is_enabled(timeout=200)
        return True, habilitado
    except Exception:
        return False, False


def corregir_campos_pendientes(page, password: str) -> dict[str, bool]:
    """
    Detecta qué campos faltan y los rellena rápidamente.
    Retorna el estado después de la corrección.
    """
    estado_final = {"password": False, "fecha_nacimiento": False, "terminos": False, "boton_suscribirse": False}
    intentos = 0
    max_intentos = 2

    while intentos < max_intentos:
        intentos += 1
        estado = verificar_registro_completo(page)
        cambios = False

        # 1. Corregir contraseña si falta
        if not estado["password"] and password:
            try:
                loc = page.locator('input[type="password"]').first
                if loc.count() and loc.is_visible(timeout=200):
                    val = loc.input_value(timeout=150)
                    if not val:
                        loc.fill(password, timeout=1000, force=True)
                        cambios = True
                    else:
                        estado_final["password"] = True
                else:
                    estado_final["password"] = True
            except Exception:
                pass
        else:
            estado_final["password"] = True

        # 2. Corregir fecha de nacimiento si falta
        if not estado["fecha_nacimiento"]:
            import random
            dia = str(random.randint(1, 28))
            mes = str(random.randint(1, 12))
            año = str(random.randint(1970, 2005))

            selects = page.locator('select').all()
            if len(selects) >= 3:
                try:
                    # Intentar asignar valores a los selects visibles
                    for i, sel in enumerate(selects[:3]):
                        try:
                            val = sel.input_value(timeout=100)
                            if not val or not val.strip():
                                if i == 0:
                                    sel.select_option(dia)
                                elif i == 1:
                                    sel.select_option(mes)
                                else:
                                    sel.select_option(año)
                                cambios = True
                        except Exception:
                            continue
                except Exception:
                    pass
            else:
                estado_final["fecha_nacimiento"] = True
        else:
            estado_final["fecha_nacimiento"] = True

        # 3. Corregir términos si faltan
        if not estado["terminos"]:
            try:
                # Buscar checkbox no marcado
                checkboxes = page.locator('input[type="checkbox"]').all()
                for cb in checkboxes:
                    try:
                        if not cb.is_checked():
                            cb.check(timeout=500)
                            cambios = True
                    except Exception:
                        continue
            except Exception:
                pass
        else:
            estado_final["terminos"] = True

        # Verificar si el botón se habilitó (inlineado)
        habilitado = False
        try:
            btn = page.locator('button:has-text("Suscríbete"), button:has-text("Subscribe")').first
            if btn.count() and btn.is_visible(timeout=150):
                habilitado = btn.is_enabled(timeout=100)
        except Exception:
            pass
        
        if habilitado:
            estado_final["boton_suscribirse"] = True
            break

        if not cambios:
            break  # No se pudo hacer más cambios

        time.sleep(0.2)  # Pequeña espera entre intentos

    return estado_final


def fase_5_completar_registro(sesiones: list[dict], passwords: list[str]) -> int:
    """
    Fase 5: Rellena contraseña, fecha de nacimiento, acepta términos y pulsa Suscríbete.
    Si el botón está deshabilitado, intenta corregir campos faltantes automáticamente.
    Retorna el número de ventanas completadas exitosamente.
    """
    sesiones_validas = [s for s in sesiones if s.get("page")]
    if not sesiones_validas:
        print("No hay ventanas abiertas para completar registro.")
        return 0

    print(f"\n=== FASE 5: Completando registro en {len(sesiones_validas)} ventana(s) ===\n")

    exitosos = 0
    for i, sesion in enumerate(sesiones_validas):
        page = sesion["page"]
        password = passwords[i] if i < len(passwords) else ""

        try:
            # 1. Rellenar contraseña (intento inicial)
            if password and rellenar_contraseña_login(page, password):
                pass  # Éxito, no mostrar aún
            else:
                print(f"[{sesion['n']}] {sesion['perfil']}: no se pudo rellenar contraseña")
                continue

            time.sleep(0.2)

            # 2. Rellenar fecha de nacimiento (intento inicial)
            rellenar_fecha_nacimiento(page)
            time.sleep(0.2)

            # 3. Aceptar términos (intento inicial)
            aceptar_terminos_privacidad(page)
            time.sleep(0.2)

            # 4. Verificar estado del botón Suscríbete (inlineado)
            visible = False
            habilitado = False
            try:
                btn = page.locator('button:has-text("Suscríbete"), button:has-text("Subscribe")').first
                if btn.count():
                    visible = btn.is_visible(timeout=200)
                    if visible:
                        habilitado = btn.is_enabled(timeout=200)
            except Exception:
                pass

            if not visible:
                print(f"[{sesion['n']}] {sesion['perfil']}: botón 'Suscríbete' no visible")
                continue

            # 5. Si botón está deshabilitado, intentar corregir automáticamente
            if not habilitado:
                print(f"[{sesion['n']}] {sesion['perfil']}: botón deshabilitado → corrigiendo...", end=" ")
                estado_corregido = corregir_campos_pendientes(page, password)

                # Verificar nuevamente (inlineado)
                habilitado_post = False
                try:
                    btn = page.locator('button:has-text("Suscríbete"), button:has-text("Subscribe")').first
                    if btn.count() and btn.is_visible(timeout=200):
                        habilitado_post = btn.is_enabled(timeout=200)
                except Exception:
                    pass

                if habilitado_post:
                    print("✓ corregido")
                else:
                    faltantes = []
                    if not estado_corregido["password"]:
                        faltantes.append("contraseña")
                    if not estado_corregido["fecha_nacimiento"]:
                        faltantes.append("fecha")
                    if not estado_corregido["terminos"]:
                        faltantes.append("términos")
                    print(f"✗ sigue bloqueado (falta: {', '.join(faltantes)})")
                    continue

            # 6. Botón habilitado, proceder a pulsar
            if pulsar_suscribirse(page):
                print(f"[{sesion['n']}] {sesion['perfil']}: registro completado ✓")
                exitosos += 1
            else:
                print(f"[{sesion['n']}] {sesion['perfil']}: error al pulsar 'Suscríbete'")

        except Exception as e:
            print(f"[{sesion['n']}] {sesion['perfil']}: error - {e}")

        time.sleep(0.2)

    print(f"\n✓ Fase 5 completada: {exitosos}/{len(sesiones_validas)} registro(s) completado(s)")
    return exitosos


def fase_6_verificar_y_navegar_suscripcion(sesiones: list[dict], emails: list[str], passwords: list[str]) -> int:
    """
    Fase 6: Verifica que todas las ventanas completaron las fases 1-5.
    Si una ventana se recargó y está incompleta, la recupera fase por fase.
    Finalmente navega al link de suscripción en todas las ventanas listas.
    Retorna el número de ventanas que navegaron exitosamente al link.
    """
    link_suscripcion = leer_link_suscripcion()
    if not link_suscripcion:
        print("\n⚠ ERROR: No se encontró link de suscripción en 'link subscription.txt'")
        print("  Crea el archivo con el URL de suscripción de TIDAL.")
        return 0

    sesiones_validas = [s for s in sesiones if s.get("page")]
    if not sesiones_validas:
        print("No hay ventanas abiertas para navegar a suscripción.")
        return 0

    print(f"\n=== FASE 6: Verificando y navegando a suscripción ===")
    print(f"Link: {link_suscripcion}\n")

    exitosos = 0
    recuperados = 0

    for i, sesion in enumerate(sesiones_validas):
        page = sesion["page"]
        email = emails[i] if i < len(emails) else ""
        password = passwords[i] if i < len(passwords) else ""
        n, perfil = sesion["n"], sesion["perfil"]

        try:
            # 1. Detectar estado actual de la ventana
            estado = detectar_estado_ventana(page, email, password)

            # Si está en página de login incompleta, necesita recuperación completa
            if estado["pagina_login"] and not estado["email_rellenado"]:
                print(f"[{n}] {perfil}: ventana recargada → recuperando...", end=" ")
                if recuperar_ventana(sesion, email, password):
                    print("✓ recuperada")
                    recuperados += 1
                else:
                    print("✗ falló recuperación")
                    continue

            # Si está en página de registro incompleta
            elif estado["pagina_registro"] and not estado["boton_suscribirse_habilitado"]:
                print(f"[{n}] {perfil}: registro incompleto → completando...", end=" ")
                if recuperar_ventana(sesion, email, password):
                    print("✓ completado")
                    recuperados += 1
                else:
                    print("✗ falló")
                    continue

            # Verificar nuevamente estado después de posible recuperación
            estado = detectar_estado_ventana(page, email, password)

            # Si ya pasó el registro o el botón está habilitado, está listo
            if estado["registro_completado"] or estado["boton_suscribirse_habilitado"]:
                # Navegar al link de suscripción
                try:
                    page.goto(link_suscripcion, timeout=15000, wait_until="domcontentloaded")
                    print(f"[{n}] {perfil}: navegado a suscripción ✓")
                    exitosos += 1
                except Exception as e:
                    print(f"[{n}] {perfil}: error al navegar - {e}")
            else:
                print(f"[{n}] {perfil}: no se pudo completar el registro")

        except Exception as e:
            print(f"[{n}] {perfil}: error - {e}")

        time.sleep(0.3)

    print(f"\n✓ Fase 6 completada: {exitosos}/{len(sesiones_validas)} navegados ({recuperados} recuperados)")
    return exitosos


def fase_7_activar_prueba_60_dias(sesiones: list[dict]) -> int:
    """
    Fase 7: En la página de suscripción, activa el toggle de
    "Amplía tu periodo de prueba 60 días por solo $76" y pulsa Continuar.
    Retorna el número de ventanas completadas exitosamente.
    """
    sesiones_validas = [s for s in sesiones if s.get("page")]
    if not sesiones_validas:
        print("No hay ventanas abiertas para activar prueba de 60 días.")
        return 0

    print(f"\n=== FASE 7: Activando prueba de 60 días en {len(sesiones_validas)} ventana(s) ===\n")

    exitosos = 0
    for sesion in sesiones_validas:
        page = sesion["page"]
        n, perfil = sesion["n"], sesion["perfil"]

        try:
            # 1. Esperar a que cargue la página de planes
            time.sleep(2.0)

            # 2. Buscar y activar el toggle de 60 días
            # El toggle está cerca del texto "60 días" o "Amplía tu periodo de prueba"
            toggle_activado = False

            # Intentar por texto cercano
            try:
                # Buscar el contenedor/label que mencione 60 días
                loc_60dias = page.locator('text=/60 días|60 days/i').first
                if loc_60dias.count():
                    # Buscar el toggle/switch cercano
                    toggle = loc_60dias.locator(
                        'xpath=ancestor::div[contains(@class, "switch")] | '
                        'xpath=ancestor::div[contains(@class, "toggle")] | '
                        'xpath=following::div[contains(@class, "switch")][1] | '
                        'xpath=preceding::div[contains(@class, "switch")][1] | '
                        'xpath=ancestor::div[1]//input[@type="checkbox"] | '
                        'xpath=ancestor::div[1]//button[contains(@role, "switch")]'
                    ).first

                    if toggle.count():
                        # Verificar si ya está activado
                        is_checked = False
                        try:
                            if toggle.input_value(timeout=100) or toggle.is_checked():
                                is_checked = True
                        except Exception:
                            pass

                        if not is_checked:
                            toggle.click(timeout=1500)
                            toggle_activado = True
                            print(f"[{n}] {perfil}: toggle 60 días activado ✓")
                        else:
                            toggle_activado = True
                            print(f"[{n}] {perfil}: toggle 60 días ya estaba activado ✓")
            except Exception:
                pass

            # Si no se encontró por texto, intentar por selectores comunes de toggle
            if not toggle_activado:
                selectores_toggle = [
                    'input[type="checkbox"]:not(:checked)',
                    'button[role="switch"][aria-checked="false"]',
                    '[class*="switch"][role="switch"][aria-checked="false"]',
                    '[class*="toggle"]:not(:checked)',
                ]
                for sel in selectores_toggle:
                    try:
                        toggle = page.locator(sel).first
                        if toggle.count() and toggle.is_visible(timeout=200):
                            toggle.click(timeout=1000)
                            toggle_activado = True
                            print(f"[{n}] {perfil}: toggle 60 días activado ✓")
                            break
                    except Exception:
                        continue

            if not toggle_activado:
                print(f"[{n}] {perfil}: no se encontró toggle de 60 días (podría estar ya activo)")

            time.sleep(0.5)

            # 3. Pulsar botón Continuar
            boton_continuar = False
            patrones_continuar = (
                re.compile(r"^\s*continuar\s*$", re.I),
                re.compile(r"^\s*continue\s*$", re.I),
                re.compile(r"^\s*siguiente\s*$", re.I),
                re.compile(r"^\s*next\s*$", re.I),
            )

            for patron in patrones_continuar:
                try:
                    btn = page.get_by_role("button", name=patron).first
                    if btn.count() and btn.is_visible(timeout=300):
                        btn.click(timeout=2000)
                        boton_continuar = True
                        print(f"[{n}] {perfil}: botón 'Continuar' pulsado ✓")
                        break
                except Exception:
                    continue

            # Intentar por selector CSS si no funcionó
            if not boton_continuar:
                selectores_btn = [
                    'button:has-text("Continuar")',
                    'button:has-text("Continue")',
                    'button[type="submit"]',
                    'button[class*="primary"]',
                ]
                for sel in selectores_btn:
                    try:
                        btn = page.locator(sel).first
                        if btn.count() and btn.is_visible(timeout=200):
                            btn.click(timeout=2000)
                            boton_continuar = True
                            print(f"[{n}] {perfil}: botón 'Continuar' pulsado ✓")
                            break
                    except Exception:
                        continue

            if toggle_activado or boton_continuar:
                exitosos += 1
            else:
                print(f"[{n}] {perfil}: no se pudo completar Fase 7")

        except Exception as e:
            print(f"[{n}] {perfil}: error - {e}")

        time.sleep(0.3)

    print(f"\n✓ Fase 7 completada: {exitosos}/{len(sesiones_validas)} ventana(s) con prueba 60 días activada")
    return exitosos


def main():
    """Función principal del creador de cuentas TIDAL."""
    print("=" * 60)
    print("CREADOR DE CUENTAS TIDAL")
    print("=" * 60)

    # Verificar que existe el archivo de links
    if not DEFAULT_LINKS_FILE.is_file():
        print(f"\nCreando archivo links.txt en: {DEFAULT_LINKS_FILE}")
        DEFAULT_LINKS_FILE.write_text(
            "# Formato: URL, NombrePerfil\nhttps://account.tidal.com/login, Profile 1\n",
            encoding="utf-8",
        )
        print("Edita links.txt y agrega los URLs de TIDAL para continuar.")
        return

    # Verificar que existe el archivo de emails
    if not DEFAULT_EMAILS_FILE.is_file():
        print(f"\nCreando archivo emails.txt en: {DEFAULT_EMAILS_FILE}")
        DEFAULT_EMAILS_FILE.write_text(
            "# Agrega aquí los emails, uno por línea (en orden correspondiente a links.txt)\n",
            encoding="utf-8",
        )
        print("Edita emails.txt y agrega los correos para continuar.")
        return

    # Leer sesiones desde links.txt
    sesiones = leer_sesiones()
    if not sesiones:
        print("No se encontraron sesiones válidas en links.txt")
        sys.exit(1)

    # Leer emails
    emails = leer_emails()
    if not emails:
        print("No se encontraron emails en emails.txt")
        sys.exit(1)

    # Leer passwords
    passwords = leer_passwords()
    if not passwords:
        print("No se encontraron contraseñas en passwords.txt")
        print("Creando archivo de ejemplo...")
        DEFAULT_PASSWORDS_FILE.write_text(
            "# Agrega aquí las contraseñas, una por línea (en orden correspondiente a links.txt)\n",
            encoding="utf-8",
        )
        sys.exit(1)

    if len(emails) < len(sesiones):
        print(f"\n⚠ Aviso: hay {len(sesiones)} ventanas pero solo {len(emails)} emails.")
        print("  Las ventanas sin email correspondiente no se completarán.")

    if len(passwords) < len(sesiones):
        print(f"\n⚠ Aviso: hay {len(sesiones)} ventanas pero solo {len(passwords)} contraseñas.")
        print("  Las ventanas sin contraseña correspondiente no se completarán.")

    with sync_playwright() as playwright:
        try:
            # === FASE 1 ===
            # Cada perfil se abre en su propio contexto aislado (perfil de Chrome separado)
            sesiones = fase_1_abrir_ventanas(playwright, sesiones)

            if not any(s.get("page") for s in sesiones):
                print("\nNo se pudieron abrir ventanas. Verifica que Chrome esté instalado.")
                sys.exit(1)

            # Verificar bloqueos después de Fase 1
            manejar_bloqueos(sesiones, "tras abrir ventanas")

            # === FASE 2 ===
            fase_2_aceptar_cookies(sesiones)

            # Verificar bloqueos después de Fase 2
            manejar_bloqueos(sesiones, "tras aceptar cookies")

            # === FASE 3 ===
            fase_3_rellenar_emails(sesiones, emails)

            # Verificar bloqueos Y completitud de Fase 3
            res3 = manejar_bloqueos_y_completitud(
                sesiones, "tras rellenar emails",
                fase_verificar="fase3_email",
                datos_verificacion={"emails": emails},
            )
            if not res3["fase_completa"]:
                print("\n  ⚠ ALERTA: Algunas ventanas no tienen el email rellenado.")
                print("  Debes rellenar manualmente o recargar la página y reintentar.")

            # === FASE 4 ===
            fase_4_pulsar_continuar(sesiones)

            # Verificar bloqueos Y completitud de Fase 4
            res4 = manejar_bloqueos_y_completitud(
                sesiones, "tras pulsar Continuar",
                fase_verificar="fase4_continuar",
            )
            if not res4["fase_completa"]:
                print("\n  ⚠ ALERTA: Algunas ventanas no avanzaron a la página de registro.")
                print("  Revisa si el botón 'Continuar' se pulsó correctamente.")

            # === FASE 5 ===
            fase_5_completar_registro(sesiones, passwords)

            # Verificar bloqueos Y completitud de Fase 5
            res5 = manejar_bloqueos_y_completitud(
                sesiones, "tras completar registro",
                fase_verificar="fase5_registro",
            )
            if not res5["fase_completa"]:
                print("\n  ⚠ ALERTA: Algunas ventanas tienen el registro incompleto.")
                print("  Indicadores: botón 'Suscríbete' en tono oscuro = campos pendientes")
                print("               botón 'Suscríbete' en tono claro/blanco = listo para pulsar")

            # === FASE 6 ===
            fase_6_verificar_y_navegar_suscripcion(sesiones, emails, passwords)

            # === FASE 7 ===
            fase_7_activar_prueba_60_dias(sesiones)

            # Proceso completado
            print("\n" + "=" * 60)
            print("¡PROCESO COMPLETADO!")
            print("Todas las fases (1-7) han sido ejecutadas.")
            print("Las ventanas tienen la prueba de 60 días activada.")
            print("=" * 60)

            # Pausa final
            pausa_manual("Proceso finalizado. Pulsa Enter para cerrar el navegador")

        except KeyboardInterrupt:
            print("\n\nScript interrumpido por el usuario.")
        finally:
            # No cerrar browser automáticamente para mantener ventanas abiertas
            pass


if __name__ == "__main__":
    main()
